# Generated by Django 4.1.7 on 2023-04-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_description'),
        ('experiences', '0003_alter_experience_category_alter_experience_host_and_more'),
        ('wishlists', '0002_alter_wishlist_experiences_alter_wishlist_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='experiences.experience'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='rooms.room'),
        ),
    ]
